### ISSUE TITLE
enable in firefox (or browsers in general)

### ISSUE THREAD

**Issue by nathanbraun** [rcmdnk/KE-complex_modifications#4]
Hi there, this is awesome, but it looks like the default is to not have it enabled in the browser?  I used the old vim emu in the browser a lot (it'd be useful for typing this issue here for example) -- is there anyway we could add an option to enable it?  Or would it be better to fork this or something?

Thanks!

**Comment by rcmdnk** [comment]
It is disabled by default for browsers (Chrome/Firefox) as they have own vim like extensions.
To change apps for vim_emu, you need to re-compile vim_emu:

* Fork this KE-complex_modifications
* Modify **scripts/erb2json.rb**
    * Remove `bundle_identifiers.concat(browser_bundle_identifiers)` from [vim_emu_exception](https://github.com/rcmdnk/KE-complex_modifications/blob/master/scripts/erb2json.rb#L283)
* Go to top directory and `make rebuild`
* Erase current vim_emu from KE (from Complex Modifications' rules and `Add rule`, too)
* Copy **docs/json/vim_emu.json** **~/.config/karabiner/assets/complex_modifications/**
* Now you can see new rules of vim_emu in KE's `Add rule`, then add them as you like

Currently, KE's setting file sets app definitions for each key set,
therefore it is not easy to modify json file directly.

**Comment by nathanbraun** [comment]
Worked like a charm (using vim emu to type this) -- thanks so much!
