### ISSUE TITLE
Can't configure "return_or_enter" to switch back to insert mode

### ISSUE THREAD

**Issue by januz** [rcmdnk/KE-complex_modifications#5]
Sorry to bother you again with questions about how to properly configure `vim_emu`...

I would like to redefine the return key to execute the return and automatically switch back to insert / OS standard mode (one of the things I use `vim_emu` for most is to replace arrow keys when selecting from lists; pressing enter is a natural endpoint to this process, so it would be great for me if I wouldn't have to manually switch back to insert mode afterwards).

I tried the following:

```
        manipulators += vim_emu(
          source_keys_list: ["return_or_enter"],
          dest_keys_list: [
              [["return_or_enter"]] + vim_emu_mode(),
          ],
          mode: "normal",
        )
```

but it doesn't do anything. When I use "spacebar" instead, it seems to work, is there something special about "return_or_enter" that prevents the setup from working? Thank you so much for your help!

**Comment by rcmdnk** [comment]
I tried your snippet and it works for me.

Maybe you have another mapping for `return_or_enter` before this setting?
Could you please try it by disabling other settings?

**Comment by januz** [comment]
Ahh, you're right. I use the modification "Change return to control if pressed with other keys, to return if pressed alone" (https://ke-complex-modifications.pqrs.org/#return_to_ctrl).

Is there a way in which I can redefine this modification within `vim_emu`? Thank you for your help!

**Comment by rcmdnk** [comment]
First, could you please update rcmdnk/KE-complex_modifications,
as I found a bug for `to_if_alone`, which is not used in current vim_emu,
but needed for the following code.

Then, could you please try following code:

        manipulators += vim_emu(
          source_keys_list: ["return_or_enter"],
          dest_keys_list: [
              [["right_control"]],
          ],
          to_if_alone: [
              [["return_or_enter"]] + vim_emu_mode(),
          ],
          mode: "normal",
        )

This enables return as **control** if alone at vim_emu normal mode.
To enable it in other situations, add a rule of **Change return to control if pressed with other keys, to return if pressed alone** `after` **Vim emulation: Vim emulation core part** in the `Rules` of `Complex modifications`.

**Comment by januz** [comment]
Worked perfectly! Thank you so much, @rcmdnk!!
